### ISSUE TITLE
Interested in making this theme compatible with other Markdown editors?

### ISSUE THREAD

**Issue by Vincendovich** [lloyd094/Typora-Law-School#6]
Hi, lloyd094, 

Really great work with the css theme. I'm very fond of this theme and plan to use it in my VS code for lab note taking (I'm a biology scientist).

I know this theme is specially wrote for Typora. I tried to add the css codes to my VS code with [Markdown Enhanced Preview](https://github.com/shd101wyy/markdown-preview-enhanced) extension, but got a very different style. 

![image](https://user-images.githubusercontent.com/38986936/63851541-4dd73800-c98e-11e9-999e-ef9c44c32921.png)

I wonder if you could help make some adaptions that can make this theme also working for VScode? I believe this would help many more others. thank you.

**Comment by lloyd094** [comment]
Hey @Vincendovich - sorry about the late reply! I haven't checked in here for a bit, and github doesn't seem to like to notify me on things...

It appears to me that you only copied the `law.css` style over, but ignored something from the `base.css` (or something else) in the folder itself. Perhaps attempt a merge of the two files? Unfortunately I don't know much about .css and how .md renders it in general (most of this theme has been figuring it out as I go), so I'm not sure where I'd start outside of Typora.

One thing that may be useful would be reaching out to the developer of the plugin and see how it renders markdown. Perhaps Typora or the extension render differently?

Feel free to reach out if you're still grappling with this and perhaps we can figure it out, or I can at least point you to the right direction (comment here or email me at lloyd094@gmail.com. For now, I will be closing this issue as it exceeds the current scope of this project.
